### ISSUE TITLE
ffmpeg can't be installed or set on Alpine

### ISSUE THREAD

**Issue by eibex** [nextcloud/recognize#1096]
### Which version of recognize are you using?

6.0.1

### Enabled Modes

Object recognition, Face recognition, Video recognition

### TensorFlow mode

Normal mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

28.0.2

### Which Operating system do you have installed?

Unraid Linux6.1.64

### Which database are you running Nextcloud on?

Postgres 15

### Which Docker container are you using to run Nextcloud? (if applicable)

28.0.2 (not AIO)

### How much RAM does your server have?

64GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

The app cannot install ffmpeg when installing it.

Additional info:

- I have ffmpeg already installed for preview generation (installed via apt)
- I used to run Recognize before moving to Docker without issues
- /tmp is mapped to tmpfs

### Expected Behavior

ffmpeg is installed and no errors are shown.

### To Reproduce

Install recognize with the [main docker container image](https://hub.docker.com/_/nextcloud).

### Debug log

```
[recognize] Error: Failed to install ffmpeg: os.js:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_homedir returned ENOENT (no such file or directory)
    at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/env-paths/index.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/ffmpeg-static/install.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -2,
    code: 'ENOENT',
    message: 'no such file or directory',
    syscall: 'uv_os_homedir'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
	POST /settings/apps/enable
	from xxx
```

**Comment by marcelklehr** [comment]
Have you tried setting the ffmpeg path in the settings?

**Comment by eibex** [comment]
I can see options to set a custom Node.js path, but not a custom ffmpeg path

**Comment by eibex** [comment]
In the config.php file I can see that the Memories app found ffmpeg without issues at under /usr/bin/ffmpeg

**Comment by eibex** [comment]
Not stale

**Comment by marcelklehr** [comment]
Ah, sorry, that was a different app with the ffmpeg path setting. Duly noted

**Comment by marcelklehr** [comment]
ffmpeg doesn't support Alpine I think. In general recognize and alpine don't work well together.

**Comment by eibex** [comment]
I tried to reinstall this today (31.0.9) and the same error is still thrown.
The docker version I've been using is the debian image btw. Not the alpine one.

As mentioned last year, ffmpeg works just fine as I install it for preview generation and the Memories app.

**Comment by eibex** [comment]
The issue is that Node.js expects the $HOME variable to be set (which it is!). Can't it just install dependencies in the apps folder? https://github.com/puppeteer/puppeteer/issues/9230

I tried creating a dummy /home/nc directory and setting $HOME to it but that doesn't seem to work.

I'm not sure how Node.js works but I think the issue is with it rather than with Recognize specifically.

**Comment by marcelklehr** [comment]
@eibex Thank you for taking the time to give feedback! I've now added a setting to allow setting the path to the ffmpeg binary manually and an autodetection mechanism for the system-installed binary.

**Comment by eibex** [comment]
I will test it when a new version comes out since the commit was done after current release. Thanks for looking more into it

Update: works fine by setting the path manually
