### ISSUE TITLE
Node.js after "One Click Installation" missing

### ISSUE THREAD

**Issue by Zipper5004** [nextcloud/recognize#1101]
### Which version of recognize are you using?

5.0.3

### Enabled Modes

Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Photos App

### Which Nextcloud version do you have installed?

27.1.5

### Which Operating system do you have installed?

Debian 11

### Which database are you running Nextcloud on?

Mariadb 10.5.23

### How much RAM does your server have?

4GiB

### What processor Architecture does your CPU have?

aarch64

### Describe the Bug

Node.js is not installed by one click installer (installation within nextcloud app framework)

### Expected Behavior

Node.js should be installed automaticly

### To Reproduce

As Nextcloud Admin go to: Apps -> Multimedia -> Recognize -> Download and enable
 -> Wait for ~14 minutes
-> Go to Administrator Setting -> Recognize
-> An error accurs on finding Node.js "Could not execute the Node.js binary. You may need to set the path to a working binary manually."
 within the unix shell I see that the directory apps/recognize/bin/ is empty

**Comment by Zipper5004** [comment]
I've tried to load it via git, but it breaks too:

```
git clone https://github.com/marcelklehr/recognize.git
Cloning into 'recognize'...
remote: Enumerating objects: 12250, done.
remote: Counting objects: 100% (1389/1389), done.
remote: Compressing objects: 100% (336/336), done.
error: 5210 bytes of body are still expected MiB | 1.39 MiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: index-pack failed
```

**Comment by Zipper5004** [comment]
Manually installing Node.js via apt sets the directory to /usr/bin/nodejs but that Node.js does not come with module promises, so I installed it globaly: sudo npm -g install promises
But I still get an error:

```
Error: Cannot find module 'fs/promises'
Require stack:
- /var/www/html/nextcloud/apps/recognize/src/classifier_faces.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/www/html/nextcloud/apps/recognize/src/classifier_faces.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/var/www/html/nextcloud/apps/recognize/src/classifier_faces.js' ]
}

Classifier process output: internal/modules/cjs/loader.js:818
  throw err;
```

**Comment by marcelklehr** [comment]
You the exact node.js version required by recognize. See the recognize admin settings
