### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by SaschaMuehl** [nextcloud/recognize#1110]
### Which version of recognize are you using?

6.1.1.

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Downstream App

Memories App

### Which Nextcloud version do you have installed?

Nextcloud Hub 7 (28.0.3)

### Which Operating system do you have installed?

Ubuntu 20.04.6 LTS 

### Which database are you running Nextcloud on?

10.6.15-MariaDB

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

48

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

"An error has occurred with face recognition, please check the Nextcloud logs."

**Nextcloud.log**
Classifier process output: internal/modules/cjs/loader.js:638 throw err; ^ Error: Cannot find module 'fs/promises' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.<anonymous> (/var/www/nextcloud/apps/recognize/src/classifier_faces.js:2:12) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3

and 

Exception: Movinet does not support WASM mode

### Expected Behavior

easy going face recognition

### To Reproduce

the failure is since a couple of updates the same. I used face recognition instead but wanted to give the app a second chance:)

**Comment by SaschaMuehl** [comment]
Just a speculation - is it maybe because of the node.js version? 

![image](https://github.com/nextcloud/recognize/assets/62723171/45191fb1-f399-487e-bfcd-35aa7a8305b5)

**Comment by SaschaMuehl** [comment]
Just updated to node.js v18 iaw https://www.stewright.me/2023/04/install-nodejs-18-on-ubuntu-22-04/

At least the face recognition (at the moment it is clustering) is working under WASM-Mode
