### ISSUE TITLE
App breaks upgrade from NC 24.0.3 to 24.0.4

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/recognize#279]
**Describe the bug**
I wanted to update my NC to 24.0.4 via `updater.phar`. During the upgrade command, an error was thrown possibly caused by the app recognize (just found out by trial and error).
I needed to disable the app recognize, execute the `occ upgrade` command.

After the upgrade was completed, the app recognize can be enabled again.

**To Reproduce**
Simply update NC 24.0.3 to 24.0.4 with the app recognize enabled

**Expected behavior**
The update runs without errors.

**Server (please complete the following information):**
 - Nextcloud: [e.g. 24.0.3]
 - OS: Ubuntu 20.04
 - RAM: 16GB
 - Processor Architecture x64

**Additional context**
Here is the complete output from `occ upgrade -vvv`

```
2022-08-12T12:43:45+02:00 Setting log level to debug
2022-08-12T12:43:45+02:00 Repair step: Repair MySQL collation
2022-08-12T12:43:45+02:00 Repair info: Not a mysql database -> nothing to do
2022-08-12T12:43:45+02:00 Repair step: Repair SQLite autoincrement
2022-08-12T12:43:45+02:00 Repair step: Copy data from accounts table when migrating from ownCloud
2022-08-12T12:43:46+02:00 Repair step: Drop account terms table when migrating from ownCloud
2022-08-12T12:43:46+02:00 Updating database schema
2022-08-12T12:43:46+02:00 Updated database
2022-08-12T12:43:46+02:00 Repair step: Repair MySQL collation
2022-08-12T12:43:46+02:00 Repair info: Not a mysql database -> nothing to do
2022-08-12T12:43:46+02:00 Repair step: Repair mime types
2022-08-12T12:43:46+02:00 Repair step: Clean tags and favorites
2022-08-12T12:43:46+02:00 Repair info: 0 tags of deleted users have been removed.
2022-08-12T12:43:46+02:00 Repair info: 0 tags for delete files have been removed.
2022-08-12T12:43:46+02:00 Repair info: 0 tag entries for deleted tags have been removed.
2022-08-12T12:43:46+02:00 Repair info: 0 tags with no entries have been removed.
2022-08-12T12:43:46+02:00 Repair step: Repair invalid shares
2022-08-12T12:43:46+02:00 Repair step: Move .step file of updater to backup location
2022-08-12T12:43:46+02:00 Repair step: Add move avatar background job
2022-08-12T12:43:46+02:00 Repair info: Repair step already executed
2022-08-12T12:43:46+02:00 Repair step: Add preview cleanup background jobs
2022-08-12T12:43:46+02:00 Repair step: Migrate oauth2_clients table to nextcloud schema
2022-08-12T12:43:47+02:00 Repair info: Update the oauth2_access_tokens table schema.
2022-08-12T12:43:48+02:00 Repair info: Update the oauth2_clients table schema.
2022-08-12T12:43:50+02:00 Repair step: Fix potential broken mount points
2022-08-12T12:43:50+02:00 Repair info: No mounts updated
2022-08-12T12:43:50+02:00 Repair step: Repair language codes
2022-08-12T12:43:50+02:00 Repair step: Install new core bundle components
2022-08-12T12:43:50+02:00 Repair step: Add log rotate job
2022-08-12T12:43:50+02:00 Repair step: Clear frontend caches
2022-08-12T12:43:50+02:00 Repair info: Image cache cleared
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\EventDispatcher\ServiceEventListener::__invoke() must be an instance of OCP\EventDispatcher\Event, instance of OC\EventDispatcher\GenericEventWrapper given, called in /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 264 and defined in /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php:65
Stack trace:
#0 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OC\EventDispatcher\ServiceEventListener->__invoke()
#1 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
#2 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#3 /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(122): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#4 /var/www/nextcloud/lib/private/Files/Node/Node.php(118): OC\EventDispatcher\SymfonyAdapter->dispatch()
#5 /var/www/nextcloud/lib/private/Files/Node/File.php(133): OC\Files\Node\Node->sendHooks()
#6 /var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php(149): OC\Files\Node\File->delete()
#7 /var/www/nextcloud/lib/private/Template/SCSSCacher.php(386): OC\Files\SimpleFS\SimpleFile->delete()
#8 /var/www/nextcloud/lib/private/Repair/ClearFrontendCaches.php(62): OC\Template\SCSSCacher->resetCache()
#9 /var/www/nextcloud/lib/private/Repair.php(124): OC\Repair\ClearFrontendCaches->run()
#10 /var/www/nextcloud/lib/private/Updater.php(293): OC\Repair->run()
#11 /var/www/nextcloud/lib/private/Updater.php(133): OC\Updater->doUpgrade()
#12 /var/www/nextcloud/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#13 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#14 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#17 /var/www/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#18 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#19 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

```

**Comment by marcelklehr** [comment]
Should be fixed by 074bb66c24d10c38f767dc5d
