### ISSUE TITLE
When classifying, it fails with error "user or password is not set" 

### ISSUE THREAD

**Issue by perebusquets** [nextcloud/recognize#325]
**Describe the bug**
It crashes when classifying. If I execute it through `occ`, the following error message is outputted: `user or password is not set`

**To Reproduce**
Not sure how it can be reproduced in this case...

**Expected behavior**
It starts recognizing images and audio.

**Recognize (please complete the following information):**
 - JS-only mode: Yes
 - Enabled modes: face, object, location, landmark

**Server (please complete the following information):**
 - Nextcloud: 24.0.4
 - OS: Alpine Linux running in Docker
 - RAM: 4GB
 - Processor Architecture: x86

**Additional context**
This is what I have on the logs:
```json
{"reqId":"WDM7lHnaSH1Ml317wLnF","level":2,"time":"2022-09-16T23:31:37+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process output: ","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}
{"reqId":"WDM7lHnaSH1Ml317wLnF","level":2,"time":"2022-09-16T23:31:38+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process errored","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}
{"reqId":"WDM7lHnaSH1Ml317wLnF","level":2,"time":"2022-09-16T23:31:38+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process error","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}

```
If someone has any idea where this is failing please let me know and I'll try to see if I can fix it... As of now, without any context, I'm not sure where to start debugging as the error message is a bit ambiguous (I'm not sure which user and password this is referring to...).
Thank you in advance for your help!

**Comment by perebusquets** [comment]
### New Update: 
I let it run overnight, and from the cronjob that runs every 30 mins I get a different error from the logs which is more specific:
```
[recognize] Warning: Classifier process output: Error: Error relocating /data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2: __memcpy_chk: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Trying js-only mode
Error: Error relocating /data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/../../deps/lib/libtensorflow.so.2: __memcpy_chk: symbol not found
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:60:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Trying js-only mode
Error: Backend name 'tensorflow' not found in registry
    at Engine.<anonymous> (/data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4254:35)
    at step (/data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:125:27)
    at Object.next (/data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:74:53)
    at /data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:67:71
    at new Promise (<anonymous>)
    at __awaiter (/data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:53:12)
    at Engine.setBackend (/data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4248:16)
    at Object.setBackend (/data/config/www/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:9001:19)
    at Object.<anonymous> (/data/config/www/nextcloud/apps/recognize/src/classifier_imagenet.js:175:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)


at 2022-09-17T12:08:07+00:00
```

**Comment by marcelklehr** [comment]
Can you try enabling WASM mode in the admin settings?

**Comment by perebusquets** [comment]
Hi! Sure, it still fails though... This time, there's no output on the logs. Here's the logs of 2 cronjob executions:
```json
{"reqId":"AOa0GziWlVedYSmS2uKI","level":2,"time":"2022-09-17T22:35:53+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process output: ","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}
{"reqId":"AOa0GziWlVedYSmS2uKI","level":2,"time":"2022-09-17T22:35:53+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process errored","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}
{"reqId":"AOa0GziWlVedYSmS2uKI","level":2,"time":"2022-09-17T22:35:53+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process error","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}
{"reqId":"uJriL94IK2gg6OxgUGxP","level":2,"time":"2022-09-17T23:11:27+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process output: ","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}
{"reqId":"uJriL94IK2gg6OxgUGxP","level":2,"time":"2022-09-17T23:11:28+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process errored","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}
{"reqId":"uJriL94IK2gg6OxgUGxP","level":2,"time":"2022-09-17T23:11:28+00:00","remoteAddr":"","user":"--","app":"recognize","method":"","url":"--","message":"Classifier process error","userAgent":"--","version":"24.0.4.1","data":{"app":"recognize"}}
```

**Comment by marcelklehr** [comment]
It seems that the "user or password is not set" error message stems from an SMB external storage. You may want to try upgrading to recognize v3 which is currently in beta to see if that fixes things. We've revamped the file crawling in v3.

**Comment by perebusquets** [comment]
Hey! I just upgraded a couple of days ago to Nextcloud Hub 3 (which comes with the Recognize v3), and the crawling seems to be working, I'm using SMB so yes, probably it was related to that. Thank you for your help!
