### ISSUE TITLE
Face Cluster in Photos does not load

### ISSUE THREAD

**Issue by illnesse** [nextcloud/recognize#393]
There's this one specific face cluster that won't open, i just get 

```
TypeError: Cannot read properties of undefined (reading 'width')
    at o.mapFileToItem (FilesListViewer.vue:235:1)
    at Array.map (<anonymous>)
    at o.fileIdsToItems (FilesListViewer.vue:164:1)
    at e.get (vue.runtime.esm.js:3415:33)
    at e.evaluate (vue.runtime.esm.js:3516:27)
    at o.fileIdsToItems (vue.runtime.esm.js:5492:25)
    at o.items (FilesListViewer.vue:206:1)
    at e.get (vue.runtime.esm.js:3415:33)
    at e.evaluate (vue.runtime.esm.js:3516:27)
    at o.items (vue.runtime.esm.js:5492:25)
```

the same face id does work in memories though, w/o any js errors, nothing in nextcloud.log either

**Comment by marcelklehr** [comment]
This is a bug in the photos app then. @skjnldsv mentioned possible issues like this one in https://github.com/nextcloud/photos/pull/1341
