### ISSUE TITLE
occ recognize:classify-images

### ISSUE THREAD

**Issue by Daddyoftwins1** [nextcloud/recognize#489]
I'm not sure if this is a bug. Or if I'm doing something incorrect. It could be I just have something configured wrong.

this is what I get after running sudo -u www-data php occ recognize:classify-images for a while. it doesn't happen right away.

Classifier process output: RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at readTags$1 (/var/www/nextcloud/apps/recognize/node_modules/exifer/dist/exifer.js:362:22)
    at parseTiffSegment (/var/www/nextcloud/apps/recognize/node_modules/exifer/dist/exifer.js:348:23)
    at Object.parseExif [as tiff] (/var/www/nextcloud/apps/recognize/node_modules/exifer/dist/exifer.js:333:9)
    at exifer (/var/www/nextcloud/apps/recognize/node_modules/exifer/dist/exifer.js:474:36)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async main (/var/www/nextcloud/apps/recognize/src/classifier_geo.js:22:21)

Result for regine-wedding-makeup11-regine-aisle.jpg = []

Failed to classify images
Classifier process timeout

the system I'm running nextcloud on 

dell-poweredge-r720xd
Memory 64GiB
processor xeon E5-2680 x 2
disk capacity 120Tb
OS UBUNTU 24.04.1 LTS 64-bit
GNOME 42.4

**Comment by marcelklehr** [comment]
Recognize v2 is no longer maintained. I recommend to deactivate it until you are able to upgrade to v3 (which only supports Nextcloud v25). Thank you for your contributions!
