### ISSUE TITLE
FFMPEG syntax error when using MusicnnModel

### ISSUE THREAD

**Issue by phil-lipp** [nextcloud/recognize#584]
### Which version of recognize are you using?

3.3.3

### Enabled Modes

Object recognition, Face recognition, Video recognition, Music recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.2

### Which Operating system do you have installed?

Debian 11

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

8GB

### What processor Architecture does your CPU have?

ARM64

### Describe the Bug

Trying to classify (using `occ recognize:classify`) results in an error.

### Expected Behavior

correctly classifying the music.

### To Reproduce

run `occ recognize:classify`

### Debug log

note: I redacted the actual path to the mp3 and replaced it with "path/to/my.mp3" where "path" would be the name of my user.

```
Classifier process output: Error: Command failed with exit code 2: /var/www/nextcloud/apps/recognize/node_modules/ffmpeg-static/ffmpeg -i /media/ext_drive_one/nextcloud/data/path/to/my.mp3 -f wav -ac 1 -ar 8000 -acodec pcm_s16le -t 120 -
/var/www/nextcloud/apps/recognize/node_modules/ffmpeg-static/ffmpeg: 1: Syntax error: word unexpected (expecting ")")


    at makeError (/var/www/nextcloud/apps/recognize/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/var/www/nextcloud/apps/recognize/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async MusicnnModel.inference (/var/www/nextcloud/apps/recognize/src/musicnn/MusicnnModel.js:47:22)
    at async main (/var/www/nextcloud/apps/recognize/src/classifier_musicnn.js:87:18) {
  shortMessage: 'Command failed with exit code 2: /var/www/nextcloud/apps/recognize/node_modules/ffmpeg-static/ffmpeg -i /media/ext_drive_one/nextcloud/data/path/to/my.mp3 -f wav -ac 1 -ar 8000 -acodec pcm_s16le -t 120 -',
  command: '/var/www/nextcloud/apps/recognize/node_modules/ffmpeg-static/ffmpeg -i /media/ext_drive_one/nextcloud/data/path/to/my.mp3 -f wav -ac 1 -ar 8000 -acodec pcm_s16le -t 120 -',
  escapedCommand: '"/var/www/nextcloud/apps/recognize/node_modules/ffmpeg-static/ffmpeg" -i "/media/ext_drive_one/nextcloud/data/path/to/my.mp3" -f wav -ac 1 -ar 8000 -acodec pcm_s16le -t 120 -',
  exitCode: 2,
  signal: undefined,
  signalDescription: undefined,
  stdout: <Buffer >,
  stderr: <Buffer 2f 76 61 72 2f 77 77 77 2f 6e 65 78 74 63 6c 6f 75 64 2f 61 70 70 73 2f 72 65 63 6f 67 6e 69 7a 65 2f 6e 6f 64 65 5f 6d 6f 64 75 6c 65 73 2f 66 66 6d ... 68 more bytes>,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by marcelklehr** [comment]
Mh, apparently the ffmpeg executable doesn't work on ARM atm. I'll look into this.
