### ISSUE TITLE
Failed to install Tensorflow.js for GPU: GPU-linux-4.1.0.tar.gz * Downloading libtensorflow

### ISSUE THREAD

**Issue by GHBLoos** [nextcloud/recognize#646]
### Which version of recognize are you using?

3.3.6

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Linux 4.18.0-372.19.1.el8_6.x86_64 x86_64

### Which Docker container are you using to run Nextcloud? (if applicable)

-

### How much RAM does your server have?

5.61 GB

### What processor Architecture does your CPU have?

AMD EPYC Processor (with IBPB) (4 cores)

### Describe the Bug

Several errors in log file related to recognize after (removing and) installing. The installation never completed on the app-page (the 'be patient turning icon' dissapeared and it didn't show as installed, but the install button was still available. After hitting the button several times with the same result, I checked the 'installed apps'. After a few times it appeared.

But the error log showed several errors:

```
[recognize] Fout: Failed to install Tensorflow.js for GPU: GPU-linux-4.1.0.tar.gz
* Downloading libtensorflow
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.9.1.tar.gz
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow_framework.so.2.9.1'
Emitted 'error' event on Unpack instance at:
    at Unpack.onerror (internal/streams/readable.js:750:14)
    at Unpack.emit (events.js:400:28)
    at Unpack.warn (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/warn-mixin.js:7:12)
    at Unpack.[onError] (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/unpack.js:325:12)
    at WriteStream.<anonymous> (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/unpack.js:381:20)
    at WriteStream.emit (events.js:400:28)
    at WriteStream.[_onerror] (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:234:10)
    at WriteStream.[_onopen] (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:249:21)
    at /var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:239:32
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow_framework.so.2.9.1'
}

POST /index.php/settings/apps/enable
from 172.20.16.64 by <DOMAIN> at 2023-01-19T20:38:48+00:00
```

---

```
[no app in context] Fout: Exception: Failed to install Tensorflow.js for GPU: GPU-linux-4.1.0.tar.gz
* Downloading libtensorflow
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.9.1.tar.gz
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow_framework.so.2.9.1'
Emitted 'error' event on Unpack instance at:
    at Unpack.onerror (internal/streams/readable.js:750:14)
    at Unpack.emit (events.js:400:28)
    at Unpack.warn (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/warn-mixin.js:7:12)
    at Unpack.[onError] (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/unpack.js:325:12)
    at WriteStream.<anonymous> (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/unpack.js:381:20)
    at WriteStream.emit (events.js:400:28)
    at WriteStream.[_onerror] (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:234:10)
    at WriteStream.[_onopen] (/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:249:21)
    at /var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:239:32
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/www/cloud.<DOMAIN>.nl/html/apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow_framework.so.2.9.1'
} at <<closure>>

 0. /var/www/cloud.<DOMAIN>.nl/html/apps/recognize/lib/Migration/InstallDeps.php line 92
    OCA\Recognize\Migration\InstallDeps->runTfjsGpuInstall()
 1. /var/www/cloud.<DOMAIN>.nl/html/lib/private/Repair.php line 127
    OCA\Recognize\Migration\InstallDeps->run()
 2. /var/www/cloud.<DOMAIN>.nl/html/lib/private/legacy/OC_App.php line 1064
    OC\Repair->run()
 3. /var/www/cloud.<DOMAIN>.nl/html/lib/private/Installer.php line 164
    OC_App::executeRepairSteps()
 4. /var/www/cloud.<DOMAIN>.nl/html/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp()
 5. /var/www/cloud.<DOMAIN>.nl/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AppSettingsController->enableApps()
 6. /var/www/cloud.<DOMAIN>.nl/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
 7. /var/www/cloud.<DOMAIN>.nl/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
 8. /var/www/cloud.<DOMAIN>.nl/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
 9. /var/www/cloud.<DOMAIN>.nl/html/lib/base.php line 1047
    OC\Route\Router->match()
10. /var/www/cloud.<DOMAIN>.nl/html/index.php line 36
    OC::handleRequest()

POST /index.php/settings/apps/enable
from 172.20.16.64 by <DOMAIN> at 2023-01-19T20:38:48+00:00
```

---

```
[PHP] Fout: Error: chmod(): No such file or directory at /var/www/cloud.<DOMAIN>.nl/html/apps/recognize/lib/Migration/InstallDeps.php#146 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /var/www/cloud.<DOMAIN>.nl/html/apps/recognize/lib/Migration/InstallDeps.php line 146
    chmod()
 2. /var/www/cloud.<DOMAIN>.nl/html/apps/recognize/lib/Migration/InstallDeps.php line 78
    OCA\Recognize\Migration\InstallDeps->testBinary()
 3. /var/www/cloud.<DOMAIN>.nl/html/lib/private/Repair.php line 127
    OCA\Recognize\Migration\InstallDeps->run()
 4. /var/www/cloud.<DOMAIN>.nl/html/lib/private/legacy/OC_App.php line 1064
    OC\Repair->run()
 5. /var/www/cloud.<DOMAIN>.nl/html/lib/private/Installer.php line 156
    OC_App::executeRepairSteps()
 6. /var/www/cloud.<DOMAIN>.nl/html/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp()
 7. /var/www/cloud.<DOMAIN>.nl/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AppSettingsController->enableApps()
 8. /var/www/cloud.<DOMAIN>.nl/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
 9. /var/www/cloud.<DOMAIN>.nl/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
10. /var/www/cloud.<DOMAIN>.nl/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
11. /var/www/cloud.<DOMAIN>.nl/html/lib/base.php line 1047
    OC\Route\Router->match()
12. /var/www/cloud.<DOMAIN>.nl/html/index.php line 36
    OC::handleRequest()

POST /index.php/settings/apps/enable
from 172.20.16.64 by <DOMAIN> at 2023-01-19T20:39:26+00:00
```

### Expected Behavior

No errors

### To Reproduce

install recognize thru the app-page

Because installing/upgrading didn't seem to work, I uninstalled and reinstalled the app

### Additional info

![image](https://user-images.githubusercontent.com/16174035/213566733-24c09ef8-9aa8-4aad-abd7-390f34381d15.png)

**Comment by marcelklehr** [comment]
Mh, I can't replicate this. Can you try installing via occ?

**Comment by GHBLoos** [comment]
Installing through occ works.
