### ISSUE TITLE
Classifier process output: sh: exec: line 0: /var/www/html/custom_apps/recognize/bin/node: not found

### ISSUE THREAD

**Issue by shalak** [nextcloud/recognize#692]
### Which version of recognize are you using?

3.5.0

### Enabled Modes

Object recognition, Face recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

25.0.3

### Which Operating system do you have installed?

Ubuntu 22.04.1 LTS

### Which Docker container are you using to run Nextcloud? (if applicable)

nextcloud-aio

### How much RAM does your server have?

16GiB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

After updating the mastercontainer, the recognize has appears to have lost its `node` installation:

```
[recognize] Warning: Classifier process output: sh: exec: line 0: /var/www/html/custom_apps/recognize/bin/node: not found
````

### Expected Behavior

Recognize works correctly

### To Reproduce

Update mastercontainer to v4.3.4

**Comment by shalak** [comment]
I entered the shell of `nextcloud-aio-nextcloud` container, and the `/var/www/html/custom_apps/recognize/bin/node` is there and it's executable.

This is the exact path that is configured in `settings/admin/recognize`
<img width="880" alt="image" src="https://user-images.githubusercontent.com/1536554/219963741-1b8f8d81-c006-4266-876f-1f47b0677576.png">

**Comment by marcelklehr** [comment]
> and it's executable

How did you test this?

**Comment by marcelklehr** [comment]
> /var/www/html/custom_apps/recognize/bin/node: No such file or directory

aha. heh :)

**Comment by shalak** [comment]
The above I executed while in `/var/www/html/custom_apps/recognize/bin/`:
```
bash-5.1# realpath node
/var/www/html/custom_apps/recognize/bin/node
```

What's going on with this file?!

**Comment by marcelklehr** [comment]
This is likely because the executable was installed when your AIO container still had gcompat installed. By now you may have updated to a newer version of AIO that doesn't come with gcompat anymore. Hence, the node executable stopped working. Reinstalling the recognize app should fix this.

**Comment by shalak** [comment]
Will reinstalling force me to recrawl all images in my NC and set up all the tags/persons again?

**Comment by shalak** [comment]
I removed the app and I went "Download and enable". It failed to install:

<details><summary>Logs</summary>
<p>

```
[recognize] Error: Failed to install Tensorflow.js for GPU: GPU-linux-4.2.0.tar.gz
* Downloading libtensorflow
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.9.1.tar.gz
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow_framework.so.2.9.1'
Emitted 'error' event on Unpack instance at:
    at Unpack.onerror (internal/streams/readable.js:750:14)
    at Unpack.emit (events.js:400:28)
    at Unpack.warn (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/warn-mixin.js:7:12)
    at Unpack.[onError] (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/unpack.js:325:12)
    at WriteStream.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/unpack.js:381:20)
    at WriteStream.emit (events.js:400:28)
    at WriteStream.[_onerror] (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:234:10)
    at WriteStream.[_onopen] (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:249:21)
    at /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:239:32
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow_framework.so.2.9.1'
}

POST /settings/apps/enable
from 10.0.0.101 by admin at 2023-02-19T17:30:34+00:00
```

```
[recognize] Error: RuntimeException: Directory /var/www/html/custom_apps/recognize/bin does not exist for sink value of /var/www/html/custom_apps/recognize/bin/x64.tar.gz at <<closure>>

 0. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 59
    GuzzleHttp\Handler\CurlFactory->applyHandlerOptions(GuzzleHttp\Handl ... l}, [[["nodejs.org"] ... "])
 1. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 43
    GuzzleHttp\Handler\CurlFactory->create("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 2. /var/www/html/lib/private/Http/Client/DnsPinMiddleware.php line 113
    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 3. /var/www/html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 35
    OC\Http\Client\DnsPinMiddleware->OC\Http\Client\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 31
    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 5. /var/www/html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 71
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 63
    GuzzleHttp\RedirectMiddleware->__invoke("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 7. /var/www/html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php line 75
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 331
    GuzzleHttp\HandlerStack->__invoke("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
 9. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 168
    GuzzleHttp\Client->transfer("*** sensitive parameters replaced ***", "*** sensitive parameters replaced ***")
10. /var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php line 187
    GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, ["/mnt/ncdata/fi ... "])
11. /var/www/html/lib/private/Http/Client/Client.php line 218
    GuzzleHttp\Client->request("get", "https://nodejs. ... z", ["/mnt/ncdata/fi ... "])
12. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 223
    OC\Http\Client\Client->get("https://nodejs. ... z", [300,"/var/www/h ... "])
13. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 101
    OCA\Recognize\Migration\InstallDeps->downloadNodeBinary("https://nodejs.org/dist/", "v14.18.2", "x64")
14. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 80
    OCA\Recognize\Migration\InstallDeps->installNodeBinary(OC\Repair {})
15. /var/www/html/lib/private/Repair.php line 127
    OCA\Recognize\Migration\InstallDeps->run(OC\Repair {})
16. /var/www/html/lib/private/legacy/OC_App.php line 1064
    OC\Repair->run()
17. /var/www/html/lib/private/Installer.php line 164
    OC_App::executeRepairSteps("recognize", ["OCA\\Recognize ... "])
18. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp("recognize")
19. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AppSettingsController->enableApps(["recognize"], [])
20. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
21. /var/www/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
22. /var/www/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, ["settings.AppSettings.enableApps"])
23. /var/www/html/lib/base.php line 1047
    OC\Route\Router->match("/settings/apps/enable")
24. /var/www/html/index.php line 36
    OC::handleRequest()

POST /settings/apps/enable
from 10.0.0.101 by admin at 2023-02-19T17:30:34+00:00
```

```
[no app in context] Error: Exception: Downloading of node binary failed at <<closure>>

 0. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 101
    OCA\Recognize\Migration\InstallDeps->downloadNodeBinary("https://nodejs.org/dist/", "v14.18.2", "x64")
 1. /var/www/html/custom_apps/recognize/lib/Migration/InstallDeps.php line 80
    OCA\Recognize\Migration\InstallDeps->installNodeBinary(OC\Repair {})
 2. /var/www/html/lib/private/Repair.php line 127
    OCA\Recognize\Migration\InstallDeps->run(OC\Repair {})
 3. /var/www/html/lib/private/legacy/OC_App.php line 1064
    OC\Repair->run()
 4. /var/www/html/lib/private/Installer.php line 164
    OC_App::executeRepairSteps("recognize", ["OCA\\Recognize ... "])
 5. /var/www/html/apps/settings/lib/Controller/AppSettingsController.php line 451
    OC\Installer->installApp("recognize")
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Settings\Controller\AppSettingsController->enableApps(["recognize"], [])
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "enableApps")
 8. /var/www/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
 9. /var/www/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, ["settings.AppSettings.enableApps"])
10. /var/www/html/lib/base.php line 1047
    OC\Route\Router->match("/settings/apps/enable")
11. /var/www/html/index.php line 36
    OC::handleRequest()

POST /settings/apps/enable
from 10.0.0.101 by admin at 2023-02-19T17:30:34+00:00
```

```
[recognize] Fatal: Error: Failed opening required '/var/www/html/custom_apps/recognize/vendor/composer/../voku/portable-utf8/bootstrap.php' (include_path='/var/www/html/custom_apps/news/vendor/pear/net_url2:/var/www/html/3rdparty/pear/archive_tar:/var/www/html/3rdparty/pear/console_getopt:/var/www/html/3rdparty/pear/pear-core-minimal/src:/var/www/html/3rdparty/pear/pear_exception:/var/www/html/apps:/var/www/html/custom_apps') at <<closure>>

0. /var/www/html/custom_apps/recognize/vendor/composer/autoload_real.php line 38
   composerRequireed7f0a1d9dc886564ddbe2945c018806("b46ad4fe52f4d1899a2951c7e6ea56b0", "/var/www/html/c ... p")
1. /var/www/html/custom_apps/recognize/vendor/autoload.php line 25
   ComposerAutoloaderInited7f0a1d9dc886564ddbe2945c018806::getLoader()
2. /var/www/html/custom_apps/recognize/lib/AppInfo/Application.php line 34
   include_once("/var/www/html/c ... p")
3. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 136
   OCA\Recognize\AppInfo\Application->register(OCP\AppFramework ... {})
4. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 91
   OC\AppFramework\Bootstrap\Coordinator->registerApps(["files","activi ... "])
5. /var/www/html/lib/base.php line 671
   OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
6. /var/www/html/lib/base.php line 1144
   OC::init()
7. /var/www/html/ocs/v1.php line 31
   require_once("/var/www/html/lib/base.php")
8. /var/www/html/ocs/v2.php line 23
   require_once("/var/www/html/ocs/v1.php")

GET /ocs/v2.php/search/providers?from=%2Fsettings%2Fadmin%2Flogging
from 10.0.0.101 at 2023-02-19T17:30:47+00:00
```

</p>
</details>

However, now the settings say the following:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/1536554/219964867-c964863b-2c2a-4b31-80df-ef0fcddb0e67.png">
<img width="875" alt="image" src="https://user-images.githubusercontent.com/1536554/219964873-6131c539-010f-427a-aa1a-7ed2b8ea8957.png">

I understand that at this point, all I have to do it wait?

**Comment by marcelklehr** [comment]
see https://github.com/nextcloud/recognize/issues/688

**Comment by marcelklehr** [comment]
> I understand that at this point, all I have to do it wait?

I suppose. You could use the occ command to download the models already.
