### ISSUE TITLE
Recognize - `Error: EACCES: permission denied`

### ISSUE THREAD

**Issue by DenuxPlays** [nextcloud/recognize#733]
### Steps to reproduce
1. Install and enable recognize from the app store.
2. Take a look at the nextcloud logs.

### Expected behavior
Do not throw and error when installing tensorflow libs.

### Actual behavior 
Throws and permission denied error.

### Host OS 
Fedora 37

#### Nextcloud AIO version
4.5.0

#### Current channel 
stable

#### Other valuable info 
Error:
```
[recognize] Error: Failed to install Tensorflow.js for GPU: GPU-linux-4.2.0.tar.gz
* Downloading libtensorflow
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.9.1.tar.gz
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, open '/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow_framework.so.2.9.1'
Emitted 'error' event on Unpack instance at:
    at Unpack.onerror (internal/streams/readable.js:750:14)
    at Unpack.emit (events.js:400:28)
    at Unpack.warn (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/warn-mixin.js:7:12)
    at Unpack.[onError] (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/unpack.js:325:12)
    at WriteStream.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/tar/lib/unpack.js:381:20)
    at WriteStream.emit (events.js:400:28)
    at WriteStream.[_onerror] (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:234:10)
    at WriteStream.[_onopen] (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:249:21)
    at /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/node_modules/fs-minipass/index.js:239:32
    at FSReqCallback.oncomplete (fs.js:179:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node-gpu/deps/lib/libtensorflow_framework.so.2.9.1'
}

POST /settings/apps/enable
from 91.1.53.169 by Denux at 2023-03-13T17:04:27+00:00
```

I do not know if this error is caused by me, the app itself or nextcloud.
How can I fix this or should I create a bug report at the recognize repo?

**Comment by marcelklehr** [comment]
Does the user that php uses have permissions to create files in the recognize folder?

**Comment by DenuxPlays** [comment]
> Does the user that php uses have permissions to create files in the recognize folder?

yes...
that was the first thing I tried. To give the user the permission

**Comment by DenuxPlays** [comment]
Any updates on this?

**Comment by DenuxPlays** [comment]
An update with the occ command instead of the App Store solved this.
