### ISSUE TITLE
Error: Call to undefined method Rubix\ML\Datasets\Labeled::features()

### ISSUE THREAD

**Issue by flintman** [nextcloud/recognize#758]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Face recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

25.0.4

### Which Operating system do you have installed?

Ubuntu 22.04

### Which Docker container are you using to run Nextcloud? (if applicable)

Not in container

### How much RAM does your server have?

16

### What processor Architecture does your CPU have?

Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 cores)

### Describe the Bug

I haven't had a working version since 3.6.0.  this is my latest issue when running sudo -u www-data php occ recognize:cluster-faces

Clustering face detections for user XXXX
ClusterDebug: Retrieving face detections for user XXXX

ClusterDebug: Found 14145 unclustered detections. Calculating clusters.
An unhandled exception has been thrown:
Error: Call to undefined method Rubix\ML\Datasets\Labeled::features() in /nextcloud/apps/recognize/lib/Clustering/DualTreeBall.php:107

### Expected Behavior

Expect to Cluster faces as descriped. 

### To Reproduce

Run command sudo -u www-data php occ recognize:cluster-faces

### Debug log

Stack trace:
#0 /nextcloud/apps/recognize/lib/Clustering/MrdBallTree.php(632): OCA\Recognize\Clustering\DualTreeBall::split()
#1 /nextcloud/apps/recognize/lib/Clustering/MstSolver.php(22): OCA\Recognize\Clustering\MrdBallTree->grow()
#2 /nextcloud/apps/recognize/lib/Clustering/HDBSCAN.php(90): OCA\Recognize\Clustering\MstSolver->__construct()
#3 /nextcloud/apps/recognize/lib/Service/FaceClusterAnalyzer.php(79): OCA\Recognize\Clustering\HDBSCAN->__construct()
#4 /nextcloud/apps/recognize/lib/Command/ClusterFaces.php(64): OCA\Recognize\Service\FaceClusterAnalyzer->calculateClusters()
#5 /nextcloud/apps/recognize/vendor/symfony/console/Command/Command.php(298): OCA\Recognize\Command\ClusterFaces->execute()
#6 /nextcloud/apps/recognize/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run()
#7 /nextcloud/apps/recognize/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#8 /nextcloud/apps/recognize/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#9 /nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run()
#10 /nextcloud/console.php(100): OC\Console\Application->run()
#11 /nextcloud/occ(11): require_once('...')

**Comment by marcelklehr** [comment]
#676
