### ISSUE TITLE
Audio recognition - Error (AIO)

### ISSUE THREAD

**Issue by pktiuk** [nextcloud/recognize#763]
### Which version of recognize are you using?

3.7.0

### Enabled Modes

Music recognition

### TensorFlow mode

WASM mode

### Which Nextcloud version do you have installed?

Nextcloud Hub 3 (25.0.4)

### Which Operating system do you have installed?

AIO, so it is alpine (i guess)

### Which Docker container are you using to run Nextcloud? (if applicable)

nextcloud/aio-nextcloud

### How much RAM does your server have?

24

### What processor Architecture does your CPU have?

ARM64 (Ampere from Oracle free tier)

### Describe the Bug

After installation and enabling selected options I got:

![image](https://user-images.githubusercontent.com/45544416/227060940-dab33fd1-5feb-451f-8f03-3b8d21cf17d8.png)
In logs I have:

```log
[recognize] Warning: Classifier process output: Error: Error relocating /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node: unsupported relocation type 7
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:72:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Trying js-only mode
Error: Error relocating /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node: unsupported relocation type 7
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:72:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12) {
  code: 'ERR_DLOPEN_FAILED'
}
Trying js-only mode
Error: Backend name 'tensorflow' not found in registry
    at Engine.<anonymous> (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4315:35)
    at step (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:140:27)
    at Object.next (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:89:53)
    at /var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:82:71
    at new Promise (<anonymous>)
    at __awaiter (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:68:12)
    at Engine.setBackend (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:4309:16)
    at Object.setBackend (/var/www/html/custom_apps/recognize/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8149:19)
    at Object.<anonymous> (/var/www/html/custom_apps/recognize/src/classifier_musicnn.js:167:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)


at 2023-03-22T23:18:52+00:00
```

### Expected Behavior

Just work

### To Reproduce

1. Install Recognize
2. Install gcompat and nodejs (on some forums people recommended installing it in case of problems)
3. Enable WASM mode (I figured out this was missing :facepalm: )
4. Reinstall (according to [comment](https://github.com/nextcloud/recognize/issues/692#issuecomment-1436044687) )
5. Enable Audio classifier

**Comment by pktiuk** [comment]
Photo recognition works well.

**Comment by mentalfl0w** [comment]
I have the same problem.
