### ISSUE TITLE
Tensorflow not built

### ISSUE THREAD

**Issue by arch-user-france1** [nextcloud/recognize#823]
### Which version of recognize are you using?

4.0.1

### Enabled Modes

Object recognition

### TensorFlow mode

Normal mode

### Which Nextcloud version do you have installed?

26.0.1

### Which Operating system do you have installed?

Fedora

### Which Docker container are you using to run Nextcloud? (if applicable)

why is this a required field, I am not using Docker for NC

### How much RAM does your server have?

40GB

### What processor Architecture does your CPU have?

x86_64

### Describe the Bug

Classifier tells me `trying js_only mode` because a module could not be found:
```
Classifier process output: Error: The Node.js native addon module (tfjs_binding.node) can not be found at path: /var/www/html/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/lib/napi-v8/tfjs_binding.node. 
Please run command 'npm rebuild @tensorflow/tfjs-node --build-addon-from-source' to rebuild the native addon module. 
If you have problem with building the addon module, please check https://github.com/tensorflow/tfjs/blob/master/tfjs-node/WINDOWS_TROUBLESHOOTING.md or file an issue.
    at Object.<anonymous> (/var/www/html/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node/dist/index.js:61:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/var/www/html/nextcloud/apps/recognize/src/efficientnet/EfficientnetModel.js:12:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
Trying js-only mode
```
<img width="1240" alt="grafik" src="https://user-images.githubusercontent.com/72965843/235371660-1d384794-907f-455b-8b5b-4f37d8a8b126.png">

### Expected Behavior

Tensorflow is built

### To Reproduce

1. Use Fedora
2. Make sure Selinux is in Enforcing mode
3. Change the node path to /bin/node

**Comment by arch-user-france1** [comment]
It seems there are permission issues.

```
(base) ➜  node_modules sudo -u nginx /bin/npm rebuild @tensorflow/tfjs-node --build-addon-from-source                                                  
[sudo] Passwort für france1: 
npm notice 
npm notice New minor version of npm available! 9.5.0 -> 9.6.5
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.5
npm notice Run npm install -g npm@9.6.5 to update!
npm notice 
npm ERR! code 1
npm ERR! path /var/www/html/nextcloud/apps/recognize/node_modules/@tensorflow/tfjs-node
npm ERR! command failed
npm ERR! command sh -c node scripts/install.js
npm ERR! CPU-linux-4.2.0.tar.gz
npm ERR! https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.9.1.tar.gz
npm ERR! node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
npm ERR! /bin/sh: Zeile 1: /var/www/html/nextcloud/apps/recognize/node_modules/.bin/node-pre-gyp: Keine Berechtigung
npm ERR! * Downloading libtensorflow
npm ERR! 
npm ERR! * Building TensorFlow Node.js bindings

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/lib/nginx/.npm/_logs/2023-04-30T19_14_27_365Z-debug-0.log
```

**Comment by marcelklehr** [comment]
Mh, node_modules/.bin/node-pre-gyp may need a +x mode?

**Comment by arch-user-france1** [comment]
I've been busy but will look into it again.

**Comment by arch-user-france1** [comment]
Indeed, the file did not have the executable bit. After setting it, I got this:
<img width="927" alt="grafik" src="https://github.com/nextcloud/recognize/assets/72965843/d3ed7c7c-7d5c-4ebb-bcf6-4866707c7875">
```
npm ERR! Error: Cannot find module '../lib/main'
npm ERR! Require stack:
npm ERR! - /var/www/html/nextcloud/apps/recognize/node_modules/.bin/node-pre-gyp
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (/var/www/html/nextcloud/apps/recognize/node_modules/.bin/node-pre-gyp:4:1)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '/var/www/html/nextcloud/apps/recognize/node_modules/.bin/node-pre-gyp'
npm ERR!   ]
npm ERR! }
```

It's still quite but not exactly the same. I don't understand what it is trying to do?

**Comment by marcelklehr** [comment]
Which node version is /bin/node ?

**Comment by arch-user-france1** [comment]
It's `v18.16.0`, a little bit older than your low requirement. For my taste, a bit too old, anyway. But, yes, it is not supported by your specifications.

**Comment by arch-user-france1** [comment]
...

**Comment by marcelklehr** [comment]
The requirement in the admin settings is not a low requirement, please do not use any node executables with a higher major version number than specified.
